-- Carmelis Studio: Storage Bucket Setup
-- Created: 2026-04-04

-- ============================================================================
-- STORAGE SETUP
-- (Bucket "gallery" must be created manually in Supabase Storage UI)
-- ============================================================================
--
-- The gallery bucket storage permissions are managed automatically by Supabase:
-- - Public bucket allows anyone to view/download images
-- - Authenticated users can upload/delete/update via RLS rules on storage.objects
-- (These are Supabase system-managed and cannot be modified via SQL)
--
